name: flutterapptemplate
description: A new Flutter application template.

productionApi: http://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/tasks
stagingApi: http://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/tasks

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true