name: flutterapptemplate
description: A new Flutter application template.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^3.2.0

  # Design
  cupertino_icons: ^0.1.2

  # Utility
  package_info: ^0.4.0+16
  equatable: ^1.1.1
  url_launcher: ^5.4.2

  # Http Client generator
  chopper: ^3.0.2

  # Serialization
  built_value: ^7.0.9

  # Dependency injection and State Management
  provider: ^4.0.4
  kiwi: ^0.2.0

  data_classes: ^3.0.0
  rxdart: ^0.23.1

  # Functional programming
  dartz: ^0.9.0-dev.5

  # Localization
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  chopper_generator: 3.0.4
  built_value_generator: ^7.0.4
  gen_lang: 0.1.0
  data_classes_generator: ^3.0.0
  kiwi_generator: ^0.4.0
  json_serializable: ^3.2.2
  flutter_translate_gen: ^1.2.1

dependency_overrides:
  analyzer: ^0.39.4
  build: ^1.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
